# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank" rel="noopener">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank" rel="noopener">@mdo</a>. Adapted by <a href="https://twitter.com/jonpitch" target="_blank" rel="noopener">@jonpitch</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

plugins:          [jekyll-paginate, jekyll-gist]

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jonpitch/progressive-hyde
